# coding: utf-8

"""
    API Shop Documentation

    Integrated API platform documentation. This document covers all services provided by API Shop. For details on common response codes (like 401, 403, 500), please refer to our unified error code documentation.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from justserpapi.api.google_api_api import GoogleAPIApi


class TestGoogleAPIApi(unittest.TestCase):
    """GoogleAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GoogleAPIApi()

    def tearDown(self) -> None:
        pass

    def test_ai_mode(self) -> None:
        """Test case for ai_mode

        Google AI Overview API
        """
        pass

    def test_ai_mode1(self) -> None:
        """Test case for ai_mode1

        Google AI Mode API
        """
        pass

    def test_autocomplete(self) -> None:
        """Test case for autocomplete

        Google Autocomplete API
        """
        pass

    def test_finance_search(self) -> None:
        """Test case for finance_search

        Google Finance Search API
        """
        pass

    def test_hotels_search(self) -> None:
        """Test case for hotels_search

        Google Images Search API
        """
        pass

    def test_hotels_search1(self) -> None:
        """Test case for hotels_search1

        Google Hotels Search API
        """
        pass

    def test_immersive_product(self) -> None:
        """Test case for immersive_product

        Google Immersive Product API
        """
        pass

    def test_jobs_search(self) -> None:
        """Test case for jobs_search

        Google Jobs Search API
        """
        pass

    def test_lens(self) -> None:
        """Test case for lens

        Google Lens API
        """
        pass

    def test_local_search(self) -> None:
        """Test case for local_search

        Google Local Search API
        """
        pass

    def test_maps_photos(self) -> None:
        """Test case for maps_photos

        Google Patents Details API
        """
        pass

    def test_maps_photos1(self) -> None:
        """Test case for maps_photos1

        Google Maps Photos API
        """
        pass

    def test_maps_places(self) -> None:
        """Test case for maps_places

        Google Maps Places API
        """
        pass

    def test_maps_posts(self) -> None:
        """Test case for maps_posts

        Google Maps Posts API
        """
        pass

    def test_maps_reviews(self) -> None:
        """Test case for maps_reviews

        Google Maps Reviews API
        """
        pass

    def test_maps_search(self) -> None:
        """Test case for maps_search

        Google Patents Search API
        """
        pass

    def test_maps_search1(self) -> None:
        """Test case for maps_search1

        Google Maps Search API
        """
        pass

    def test_news_search(self) -> None:
        """Test case for news_search

        Google News Search API
        """
        pass

    def test_scholar_author(self) -> None:
        """Test case for scholar_author

        Google Scholar Author API
        """
        pass

    def test_scholar_cite_search(self) -> None:
        """Test case for scholar_cite_search

        Google Scholar Cite Search API
        """
        pass

    def test_scholar_profiles(self) -> None:
        """Test case for scholar_profiles

        Google Scholar Profiles API
        """
        pass

    def test_scholar_search(self) -> None:
        """Test case for scholar_search

        Google Scholar Search API
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Google Search API
        """
        pass

    def test_search_light(self) -> None:
        """Test case for search_light

        Google Light Search API
        """
        pass

    def test_search_mobile(self) -> None:
        """Test case for search_mobile

        Google Mobile Search API
        """
        pass

    def test_shopping_search(self) -> None:
        """Test case for shopping_search

        Google Shopping Search API
        """
        pass

    def test_shorts_search(self) -> None:
        """Test case for shorts_search

        Google Shorts Search API
        """
        pass

    def test_trends_autocomplete(self) -> None:
        """Test case for trends_autocomplete

        Google Trends Autocomplete API
        """
        pass

    def test_trends_search(self) -> None:
        """Test case for trends_search

        Google Trends Search API
        """
        pass

    def test_trends_trending_now(self) -> None:
        """Test case for trends_trending_now

        Google Trends Trending Now API
        """
        pass

    def test_videos_search(self) -> None:
        """Test case for videos_search

        Google Videos Search API
        """
        pass


if __name__ == '__main__':
    unittest.main()
