# coding: utf-8

# flake8: noqa
"""
    API Shop Documentation

    Integrated API platform documentation. This document covers all services provided by API Shop. For details on common response codes (like 401, 403, 500), please refer to our unified error code documentation.

    The version of the OpenAPI document: v1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package

